services:
  postgres:
    image: postgres:16
    container_name: food-delivery-postgres
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_pass
    ports:
      - "5433:5432"